import css from './CreateNote.module.css'
import NoteForm from '@/components/NoteForm/NoteForm';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create new note(-s)',
  description: 'Generated by create note with tag',
  openGraph: {
  title: 'Create new note(-s)',
  description: 'Generated by create note with tag',
    url: 'https://08-zustand-pjby04yom-daria-hs-projects.vercel.app/notes/action/create',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
        width: 1200,
        height: 630,
        alt: 'NoteHub image logo',
      },
    ],
  },
};


export default async function CreateNote() {
  return (
    <main className={css.main}>
      <div className={css.container}>
        <h1 className={css.title}>Create note</h1>
        <NoteForm />
      </div>
    </main>
  );
}